import type { DashboardWidgetDefinition } from "./dashboard.types";

export const DASHBOARD_WIDGETS: DashboardWidgetDefinition[] = [
  {
    id: "reportRuns",
    kind: "usage",
    title: "Corridas de reportes",
    subtitle: "Mes actual",
    icon: "chart-line",
    accentClass: "text-violet-600",
    metricKey: "reportRuns",
    limitKey: "maxReportRunsPerMonth",
    href: "/reports",
  },
  {
    id: "emailsSent",
    kind: "usage",
    title: "Correos enviados",
    subtitle: "Mes actual",
    icon: "envelope",
    accentClass: "text-emerald-600",
    metricKey: "emailsSent",
    limitKey: "maxEmailsPerMonth",
    href: "/reports",
  },
  {
    id: "storageBytesUsed",
    kind: "usage",
    title: "Almacenamiento generado",
    subtitle: "Mes actual",
    icon: "database",
    accentClass: "text-orange-600",
    metricKey: "storageBytesUsed",
    limitKey: "maxStorageBytes",
    valueFormat: "bytes",
    href: "/system/billing",
  },
  {
    id: "tripsCreated",
    kind: "usage",
    title: "Viajes creados",
    subtitle: "Mes actual",
    icon: "truck",
    accentClass: "text-sky-600",
    metricKey: "tripsCreated",
    limitKey: "maxTripsPerMonth",
    href: "/transport/trips",
  },
  {
    id: "tripsCount",
    kind: "collection",
    title: "Viajes (colección)",
    subtitle: "Tenant activo",
    icon: "car",
    accentClass: "text-blue-600",
    collectionName: "trips",
    href: "/transport/trips",
  },
  {
    id: "reportsCount",
    kind: "collection",
    title: "Reportes ejecutados",
    subtitle: "Tenant activo",
    icon: "file",
    accentClass: "text-purple-600",
    collectionName: "report-runs",
    href: "/reports",
  },
  {
    id: "settlementsCount",
    kind: "collection",
    title: "Liquidaciones",
    subtitle: "Tenant activo",
    icon: "wallet",
    accentClass: "text-cyan-600",
    collectionName: "settlements",
    href: "/transport/settlements",
  },
  {
    id: "clientsCount",
    kind: "collection",
    title: "Clientes",
    subtitle: "Tenant activo",
    icon: "users",
    accentClass: "text-indigo-600",
    collectionName: "clients",
    href: "/master/clients",
  },
];

